include_recipe "./recipes/packages.rb"
include_recipe "./recipes/homebrew.rb"
include_recipe "./recipes/languages.rb"
include_recipe "./recipes/gems.rb"
include_recipe "./recipes/pip.rb"
include_recipe "./recipes/ghq.rb"
include_recipe "./recipes/git_config.rb"
