class Specinfra::Command::Pop < Specinfra::Command::Ubuntu; end

include_recipe "./recipes/homebrew.rb"
# TODO: check linux
# include_recipe "./recipes/linuxbrew.rb" if node[:platform] == "pop"
include_recipe "./recipes/mac_packages.rb" if node[:platform] == "darwin"
include_recipe "./recipes/mkdir.rb"
include_recipe "./recipes/default_libs.rb"
include_recipe "./recipes/mise.rb"
include_recipe "./recipes/gh_release.rb"
include_recipe "./recipes/git_config.rb"
include_recipe "./recipes/tig_config.rb"
include_recipe "./recipes/ssh.rb"
include_recipe "./recipes/scripts.rb" if node[:platform] == "pop"
include_recipe "./recipes/dropbox_link.rb"
include_recipe "./recipes/git.rb"
include_recipe "./recipes/fish_link.rb"
include_recipe "./recipes/add_apt_repository.rb" if node[:platform] == "pop"
include_recipe "./recipes/packages.rb" if node[:platform] == "pop"

# language
# include_recipe "./recipes/rustup.rb"
# include_recipe "./recipes/nodebrew.rb"
# include_recipe "./recipes/rbenv.rb"
# include_recipe "./recipes/pyenv.rb"
# include_recipe "./recipes/goenv.rb"

include_recipe "./recipes/symlink.rb" if node[:platform] == "pop"
include_recipe "./recipes/ghq.rb"
include_recipe "./recipes/packages_with_build.rb"
include_recipe "./recipes/flatpak.rb" if node[:platform] == "pop"
include_recipe "./recipes/ghq_link.rb"
# include_recipe "./recipes/asdf.rb"
# include_recipe "./recipes/pip.rb"
include_recipe "./recipes/npm.rb"
include_recipe "./recipes/vim.rb"
include_recipe "./recipes/font.rb"
include_recipe "./recipes/key_setting.rb" if node[:platform] == "pop"
include_recipe "./recipes/usr_local_link.rb" if node[:platform] == "pop"
# include_recipe "./recipes/tfenv.rb"
# include_recipe "./recipes/ngrok.rb"
