include_recipe "./recipes/git_config.rb"
include_recipe "./recipes/tig_config.rb"
include_recipe "./recipes/scripts.rb" if node[:platform] == "ubuntu"
include_recipe "./recipes/dropbox_link.rb"
include_recipe "./recipes/git.rb"
include_recipe "./recipes/fish_link.rb"
include_recipe "./recipes/homebrew.rb" if node[:platform] == "darwin"
include_recipe "./recipes/linuxbrew.rb" if node[:platform] == "ubuntu"
include_recipe "./recipes/packages.rb"
include_recipe "./recipes/languages.rb"
include_recipe "./recipes/ghq.rb"
include_recipe "./recipes/packages_with_build.rb"
include_recipe "./recipes/ghq_link.rb"
include_recipe "./recipes/pip.rb"
include_recipe "./recipes/npm.rb"
include_recipe "./recipes/vim_installer.rb" if node[:platform] == "ubuntu"
include_recipe "./recipes/vim.rb"
include_recipe "./recipes/font.rb"
